//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameworkControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventFrameworkControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonPressed {
            get {
                object obj = ResourceManager.GetObject("buttonPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonState {
            get {
                object obj = ResourceManager.GetObject("buttonState", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buttonStatePressed {
            get {
                object obj = ResourceManager.GetObject("buttonStatePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;!--to publish an event to the event-framework, send this SOAP-Request-Message to the following endpoint:
        ///##endpoint##
        ///If successful, this function-call will return &lt;CallReturn&gt;1&lt;/CallReturn&gt;, else &lt;CallReturn&gt;0&lt;/CallReturn&gt;.--&gt;
        ///&lt;SOAP:Envelope
        /// xmlns:xsi=&apos;http://www.w3.org/1999/XMLSchema-instance&apos;
        /// xmlns:xsd=&apos;http://www.w3.org/1999/XMLSchema&apos;
        /// xmlns:SOAP=&apos;urn:schemas-xmlsoap-org:soap.v1&apos;
        /// xmlns:dt=&apos;urn:schemas-microsoft-com:datatypes&apos;&gt;
        ///	&lt;SOAP:Body&gt;
        ///		&lt;cli:EVENT_FRAMEWORK_INS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newEventSoapRequest {
            get {
                return ResourceManager.GetString("newEventSoapRequest", resourceCulture);
            }
        }
    }
}
