//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventFrameworkControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.pipe://WIN-N26JO1512TH/EventServiceProxy")]
        public string netPipeAddress {
            get {
                return ((string)(this["netPipeAddress"]));
            }
            set {
                this["netPipeAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://WIN-N26JO1512TH:1234/EventServiceProxy")]
        public string netTcpAddress {
            get {
                return ((string)(this["netTcpAddress"]));
            }
            set {
                this["netTcpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DSInstance, TriggerID, TriggerType, TriggerName, Description, Statement, Internal" +
            "Source, Values, CreatedBy")]
        public string atomicEvViewCols {
            get {
                return ((string)(this["atomicEvViewCols"]));
            }
            set {
                this["atomicEvViewCols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActionID, WsdlAddress, MethodeName, Description, ParamDescr, ReturnDescr, SparqlQ" +
            "uery, CreatedBy")]
        public string actionViewCols {
            get {
                return ((string)(this["actionViewCols"]));
            }
            set {
                this["actionViewCols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CEID, Name, Description, IsActive, IsOverlapping, Period, Recurrences")]
        public string complexEvViewCols {
            get {
                return ((string)(this["complexEvViewCols"]));
            }
            set {
                this["complexEvViewCols"] = value;
            }
        }
    }
}
