//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuosoEventService.VirtuosoCentral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8890/EventFrameworkProcedures/services.wsdl", ConfigurationName="VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType")]
    public interface EventFrameworkProceduresDocLiteralPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_INSERT_NEW_EVENT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse EVENT_FRAMEWORK_INSERT_NEW_EVENT(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_GET_SCHEMA_TABLES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse EVENT_FRAMEWORK_GET_SCHEMA_TABLES(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message ERR_MAIL_SENDRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#ERR_MAIL_SEND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDResponse ERR_MAIL_SEND(VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_INSERT_TTL_DATARequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_INSERT_TTL_DATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATAResponse EVENT_FRAMEWORK_INSERT_TTL_DATA(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATARequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message VFS_ROBOTS_GETRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#VFS_ROBOTS_GET", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETResponse VFS_ROBOTS_GET(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_SPARQL_TO_SQLRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_SPARQL_TO_SQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLResponse EVENT_FRAMEWORK_SPARQL_TO_SQL(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_TEST_SQL_CONDITION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse EVENT_FRAMEWORK_TEST_SQL_CONDITION(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_DROP_TRIGGERRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_DROP_TRIGGER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERResponse EVENT_FRAMEWORK_DROP_TRIGGER(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_GET_NEXT_IDRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_GET_NEXT_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDResponse EVENT_FRAMEWORK_GET_NEXT_ID(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message VFS_ROBOTS_PARSERequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#VFS_ROBOTS_PARSE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSEResponse VFS_ROBOTS_PARSE(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_REGISTER_DBRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_REGISTER_DB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBResponse EVENT_FRAMEWORK_REGISTER_DB(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_SET_NEW_TRIGGER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse EVENT_FRAMEWORK_SET_NEW_TRIGGER(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_INSERT_CONSTANTRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_INSERT_CONSTANT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTResponse EVENT_FRAMEWORK_INSERT_CONSTANT(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_GET_GRAPHSRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_GET_GRAPHS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSResponse EVENT_FRAMEWORK_GET_GRAPHS(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_INTERNAL_SPARQLRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_INTERNAL_SPARQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLResponse EVENT_FRAMEWORK_INTERNAL_SPARQL(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INSERT_NEW_EVENT", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dsInstance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string internalSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime occ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rowVector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ceid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int trigg;
        
        public EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest() {
        }
        
        public EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest(int dsInstance, string internalSource, string name, System.DateTime occ, string rowVector, int ceid, int trigg) {
            this.dsInstance = dsInstance;
            this.internalSource = internalSource;
            this.name = name;
            this.occ = occ;
            this.rowVector = rowVector;
            this.ceid = ceid;
            this.trigg = trigg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse() {
        }
        
        public EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_SCHEMA_TABLES", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        public EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest() {
        }
        
        public EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest(int controlID) {
            this.controlID = controlID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CallReturn;
        
        public EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse() {
        }
        
        public EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse(string[] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ERR_MAIL_SEND", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class ERR_MAIL_SENDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _tgt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _urls;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _root;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _stat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _msg;
        
        public ERR_MAIL_SENDRequest() {
        }
        
        public ERR_MAIL_SENDRequest(string _tgt, string _urls, string _root, string _stat, string _msg) {
            this._tgt = _tgt;
            this._urls = _urls;
            this._root = _root;
            this._stat = _stat;
            this._msg = _msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ERR_MAIL_SENDResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class ERR_MAIL_SENDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public ERR_MAIL_SENDResponse() {
        }
        
        public ERR_MAIL_SENDResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggername;
        
        public EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest() {
        }
        
        public EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest(int controlID, string tablename, string triggername) {
            this.controlID = controlID;
            this.tablename = tablename;
            this.triggername = triggername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse() {
        }
        
        public EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INSERT_TTL_DATA", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INSERT_TTL_DATARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ttl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string graph;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filePathFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filePathTo;
        
        public EVENT_FRAMEWORK_INSERT_TTL_DATARequest() {
        }
        
        public EVENT_FRAMEWORK_INSERT_TTL_DATARequest(int controlID, string ttl, string graph, string filePath, int filePathFrom, int filePathTo) {
            this.controlID = controlID;
            this.ttl = ttl;
            this.graph = graph;
            this.filePath = filePath;
            this.filePathFrom = filePathFrom;
            this.filePathTo = filePathTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INSERT_TTL_DATAResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INSERT_TTL_DATAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_INSERT_TTL_DATAResponse() {
        }
        
        public EVENT_FRAMEWORK_INSERT_TTL_DATAResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_GET", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_GETRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _host;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _root;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double site_delay_sec;
        
        public VFS_ROBOTS_GETRequest() {
        }
        
        public VFS_ROBOTS_GETRequest(string _host, string _root, double site_delay_sec) {
            this._host = _host;
            this._root = _root;
            this.site_delay_sec = site_delay_sec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_GETResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_GETResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double site_delay_sec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public VFS_ROBOTS_GETResponse() {
        }
        
        public VFS_ROBOTS_GETResponse(double site_delay_sec, string CallReturn) {
            this.site_delay_sec = site_delay_sec;
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_SPARQL_TO_SQL", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_SPARQL_TO_SQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string syntax;
        
        public EVENT_FRAMEWORK_SPARQL_TO_SQLRequest() {
        }
        
        public EVENT_FRAMEWORK_SPARQL_TO_SQLRequest(string syntax) {
            this.syntax = syntax;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_SPARQL_TO_SQLResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_SPARQL_TO_SQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_SPARQL_TO_SQLResponse() {
        }
        
        public EVENT_FRAMEWORK_SPARQL_TO_SQLResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_TEST_SQL_CONDITION", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string executeQuerry;
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest() {
        }
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest(string executeQuerry) {
            this.executeQuerry = executeQuerry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] CallReturn;
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse() {
        }
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse(string[][] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_DROP_TRIGGER", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_DROP_TRIGGERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggername;
        
        public EVENT_FRAMEWORK_DROP_TRIGGERRequest() {
        }
        
        public EVENT_FRAMEWORK_DROP_TRIGGERRequest(int controlID, string triggername) {
            this.controlID = controlID;
            this.triggername = triggername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_DROP_TRIGGERResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_DROP_TRIGGERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_DROP_TRIGGERResponse() {
        }
        
        public EVENT_FRAMEWORK_DROP_TRIGGERResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_NEXT_ID", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_NEXT_IDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idColumn;
        
        public EVENT_FRAMEWORK_GET_NEXT_IDRequest() {
        }
        
        public EVENT_FRAMEWORK_GET_NEXT_IDRequest(string tablename, string idColumn) {
            this.tablename = tablename;
            this.idColumn = idColumn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_NEXT_IDResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_NEXT_IDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CallReturn;
        
        public EVENT_FRAMEWORK_GET_NEXT_IDResponse() {
        }
        
        public EVENT_FRAMEWORK_GET_NEXT_IDResponse(int CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tableName;
        
        public EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest() {
        }
        
        public EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest(int controlID, string tableName) {
            this.controlID = controlID;
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CallReturn;
        
        public EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse() {
        }
        
        public EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse(string[] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_PARSE", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_PARSERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string txt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ua;
        
        public VFS_ROBOTS_PARSERequest() {
        }
        
        public VFS_ROBOTS_PARSERequest(string txt, string ua) {
            this.txt = txt;
            this.ua = ua;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_PARSEResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_PARSEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double delay_sec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public VFS_ROBOTS_PARSEResponse() {
        }
        
        public VFS_ROBOTS_PARSEResponse(double delay_sec, string CallReturn) {
            this.delay_sec = delay_sec;
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_REGISTER_DB", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_REGISTER_DBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dbInstance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endpointAdd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thisEndpoint;
        
        public EVENT_FRAMEWORK_REGISTER_DBRequest() {
        }
        
        public EVENT_FRAMEWORK_REGISTER_DBRequest(int controlID, int dbInstance, string endpointAdd, string thisEndpoint) {
            this.controlID = controlID;
            this.dbInstance = dbInstance;
            this.endpointAdd = endpointAdd;
            this.thisEndpoint = thisEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_REGISTER_DBResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_REGISTER_DBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_REGISTER_DBResponse() {
        }
        
        public EVENT_FRAMEWORK_REGISTER_DBResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggername;
        
        public EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest() {
        }
        
        public EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest(int controlID, string tablename, string triggername) {
            this.controlID = controlID;
            this.tablename = tablename;
            this.triggername = triggername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse() {
        }
        
        public EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_SET_NEW_TRIGGER", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggerStatement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggerType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paramArray;
        
        public EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest() {
        }
        
        public EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest(int controlID, string triggerStatement, string tableName, string triggerName, string triggerType, string condition, string paramArray) {
            this.controlID = controlID;
            this.triggerStatement = triggerStatement;
            this.tableName = tableName;
            this.triggerName = triggerName;
            this.triggerType = triggerType;
            this.condition = condition;
            this.paramArray = paramArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse() {
        }
        
        public EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INSERT_CONSTANT", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INSERT_CONSTANTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyV;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valueV;
        
        public EVENT_FRAMEWORK_INSERT_CONSTANTRequest() {
        }
        
        public EVENT_FRAMEWORK_INSERT_CONSTANTRequest(int controlID, string keyV, string valueV) {
            this.controlID = controlID;
            this.keyV = keyV;
            this.valueV = valueV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INSERT_CONSTANTResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INSERT_CONSTANTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public EVENT_FRAMEWORK_INSERT_CONSTANTResponse() {
        }
        
        public EVENT_FRAMEWORK_INSERT_CONSTANTResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        public EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest() {
        }
        
        public EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest(int controlID, string tablename) {
            this.controlID = controlID;
            this.tablename = tablename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CallReturn;
        
        public EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse() {
        }
        
        public EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse(string[] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_GRAPHS", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_GRAPHSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        public EVENT_FRAMEWORK_GET_GRAPHSRequest() {
        }
        
        public EVENT_FRAMEWORK_GET_GRAPHSRequest(int controlID) {
            this.controlID = controlID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_GET_GRAPHSResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_GET_GRAPHSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CallReturn;
        
        public EVENT_FRAMEWORK_GET_GRAPHSResponse() {
        }
        
        public EVENT_FRAMEWORK_GET_GRAPHSResponse(string[] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INTERNAL_SPARQL", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INTERNAL_SPARQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int controlID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string executeQuerry;
        
        public EVENT_FRAMEWORK_INTERNAL_SPARQLRequest() {
        }
        
        public EVENT_FRAMEWORK_INTERNAL_SPARQLRequest(int controlID, string executeQuerry) {
            this.controlID = controlID;
            this.executeQuerry = executeQuerry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_INTERNAL_SPARQLResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_INTERNAL_SPARQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] CallReturn;
        
        public EVENT_FRAMEWORK_INTERNAL_SPARQLResponse() {
        }
        
        public EVENT_FRAMEWORK_INTERNAL_SPARQLResponse(string[][] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventFrameworkProceduresDocLiteralPortTypeChannel : VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventFrameworkProceduresDocLiteralPortTypeClient : System.ServiceModel.ClientBase<VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType>, VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType {
        
        public EventFrameworkProceduresDocLiteralPortTypeClient() {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_INSERT_NEW_EVENT(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest request) {
            return base.Channel.EVENT_FRAMEWORK_INSERT_NEW_EVENT(request);
        }
        
        public string EVENT_FRAMEWORK_INSERT_NEW_EVENT(int dsInstance, string internalSource, string name, System.DateTime occ, string rowVector, int ceid, int trigg) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest();
            inValue.dsInstance = dsInstance;
            inValue.internalSource = internalSource;
            inValue.name = name;
            inValue.occ = occ;
            inValue.rowVector = rowVector;
            inValue.ceid = ceid;
            inValue.trigg = trigg;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_INSERT_NEW_EVENT(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_GET_SCHEMA_TABLES(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest request) {
            return base.Channel.EVENT_FRAMEWORK_GET_SCHEMA_TABLES(request);
        }
        
        public string[] EVENT_FRAMEWORK_GET_SCHEMA_TABLES(int controlID) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest();
            inValue.controlID = controlID;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_GET_SCHEMA_TABLES(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.ERR_MAIL_SEND(VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest request) {
            return base.Channel.ERR_MAIL_SEND(request);
        }
        
        public string ERR_MAIL_SEND(string _tgt, string _urls, string _root, string _stat, string _msg) {
            VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest inValue = new VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest();
            inValue._tgt = _tgt;
            inValue._urls = _urls;
            inValue._root = _root;
            inValue._stat = _stat;
            inValue._msg = _msg;
            VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).ERR_MAIL_SEND(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest request) {
            return base.Channel.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(request);
        }
        
        public string EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(int controlID, string tablename, string triggername) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest();
            inValue.controlID = controlID;
            inValue.tablename = tablename;
            inValue.triggername = triggername;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATAResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_INSERT_TTL_DATA(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATARequest request) {
            return base.Channel.EVENT_FRAMEWORK_INSERT_TTL_DATA(request);
        }
        
        public string EVENT_FRAMEWORK_INSERT_TTL_DATA(int controlID, string ttl, string graph, string filePath, int filePathFrom, int filePathTo) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATARequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATARequest();
            inValue.controlID = controlID;
            inValue.ttl = ttl;
            inValue.graph = graph;
            inValue.filePath = filePath;
            inValue.filePathFrom = filePathFrom;
            inValue.filePathTo = filePathTo;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_TTL_DATAResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_INSERT_TTL_DATA(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.VFS_ROBOTS_GET(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest request) {
            return base.Channel.VFS_ROBOTS_GET(request);
        }
        
        public string VFS_ROBOTS_GET(string _host, string _root, ref double site_delay_sec) {
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest inValue = new VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest();
            inValue._host = _host;
            inValue._root = _root;
            inValue.site_delay_sec = site_delay_sec;
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).VFS_ROBOTS_GET(inValue);
            site_delay_sec = retVal.site_delay_sec;
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_SPARQL_TO_SQL(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLRequest request) {
            return base.Channel.EVENT_FRAMEWORK_SPARQL_TO_SQL(request);
        }
        
        public string EVENT_FRAMEWORK_SPARQL_TO_SQL(string syntax) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLRequest();
            inValue.syntax = syntax;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SPARQL_TO_SQLResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_SPARQL_TO_SQL(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_TEST_SQL_CONDITION(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest request) {
            return base.Channel.EVENT_FRAMEWORK_TEST_SQL_CONDITION(request);
        }
        
        public string[][] EVENT_FRAMEWORK_TEST_SQL_CONDITION(string executeQuerry) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest();
            inValue.executeQuerry = executeQuerry;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_TEST_SQL_CONDITION(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_DROP_TRIGGER(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERRequest request) {
            return base.Channel.EVENT_FRAMEWORK_DROP_TRIGGER(request);
        }
        
        public string EVENT_FRAMEWORK_DROP_TRIGGER(int controlID, string triggername) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERRequest();
            inValue.controlID = controlID;
            inValue.triggername = triggername;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_DROP_TRIGGERResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_DROP_TRIGGER(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_GET_NEXT_ID(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDRequest request) {
            return base.Channel.EVENT_FRAMEWORK_GET_NEXT_ID(request);
        }
        
        public int EVENT_FRAMEWORK_GET_NEXT_ID(string tablename, string idColumn) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDRequest();
            inValue.tablename = tablename;
            inValue.idColumn = idColumn;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_NEXT_IDResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_GET_NEXT_ID(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest request) {
            return base.Channel.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE(request);
        }
        
        public string[] EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE(int controlID, string tableName) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLERequest();
            inValue.controlID = controlID;
            inValue.tableName = tableName;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLEResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_GET_COLUMNS_OF_TABLE(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSEResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.VFS_ROBOTS_PARSE(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest request) {
            return base.Channel.VFS_ROBOTS_PARSE(request);
        }
        
        public double VFS_ROBOTS_PARSE(string txt, string ua, out string CallReturn) {
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest inValue = new VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest();
            inValue.txt = txt;
            inValue.ua = ua;
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSEResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).VFS_ROBOTS_PARSE(inValue);
            CallReturn = retVal.CallReturn;
            return retVal.delay_sec;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_REGISTER_DB(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBRequest request) {
            return base.Channel.EVENT_FRAMEWORK_REGISTER_DB(request);
        }
        
        public string EVENT_FRAMEWORK_REGISTER_DB(int controlID, int dbInstance, string endpointAdd, string thisEndpoint) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBRequest();
            inValue.controlID = controlID;
            inValue.dbInstance = dbInstance;
            inValue.endpointAdd = endpointAdd;
            inValue.thisEndpoint = thisEndpoint;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_REGISTER_DBResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_REGISTER_DB(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest request) {
            return base.Channel.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(request);
        }
        
        public string EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(int controlID, string tablename, string triggername) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest();
            inValue.controlID = controlID;
            inValue.tablename = tablename;
            inValue.triggername = triggername;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_SET_NEW_TRIGGER(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest request) {
            return base.Channel.EVENT_FRAMEWORK_SET_NEW_TRIGGER(request);
        }
        
        public string EVENT_FRAMEWORK_SET_NEW_TRIGGER(int controlID, string triggerStatement, string tableName, string triggerName, string triggerType, string condition, string paramArray) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest();
            inValue.controlID = controlID;
            inValue.triggerStatement = triggerStatement;
            inValue.tableName = tableName;
            inValue.triggerName = triggerName;
            inValue.triggerType = triggerType;
            inValue.condition = condition;
            inValue.paramArray = paramArray;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_SET_NEW_TRIGGER(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_INSERT_CONSTANT(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTRequest request) {
            return base.Channel.EVENT_FRAMEWORK_INSERT_CONSTANT(request);
        }
        
        public string EVENT_FRAMEWORK_INSERT_CONSTANT(int controlID, string keyV, string valueV) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTRequest();
            inValue.controlID = controlID;
            inValue.keyV = keyV;
            inValue.valueV = valueV;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INSERT_CONSTANTResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_INSERT_CONSTANT(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest request) {
            return base.Channel.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(request);
        }
        
        public string[] EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(int controlID, string tablename) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest();
            inValue.controlID = controlID;
            inValue.tablename = tablename;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_GET_GRAPHS(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSRequest request) {
            return base.Channel.EVENT_FRAMEWORK_GET_GRAPHS(request);
        }
        
        public string[] EVENT_FRAMEWORK_GET_GRAPHS(int controlID) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSRequest();
            inValue.controlID = controlID;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_GET_GRAPHSResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_GET_GRAPHS(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_INTERNAL_SPARQL(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLRequest request) {
            return base.Channel.EVENT_FRAMEWORK_INTERNAL_SPARQL(request);
        }
        
        public string[][] EVENT_FRAMEWORK_INTERNAL_SPARQL(int controlID, string executeQuerry) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLRequest();
            inValue.controlID = controlID;
            inValue.executeQuerry = executeQuerry;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_INTERNAL_SPARQLResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_INTERNAL_SPARQL(inValue);
            return retVal.CallReturn;
        }
    }
}
